### ISSUE TITLE
File I/O + Hours Missed count

### ISSUE THREAD

**Issue by AmbiguousCat** [parkerokonek/enteral-feeding#15]
Patient Files are structured as follows: (in README)

Name:
Feeding Type:
Total Daily Volume:
Max Feeding Rate:
Start: Y M D h Stop: Y M D h
Start: Y M D h Stop: Y M D h

New data type
timeblock:
    Y
    M
    D
    h

New function for timeline stuff:
- Use when daily reset.
OR
- Use when loading new patient file.

int hoursmissedtotal = 0

Day start time(daystart) = Y=currentyear M=currentmonth D=currentday resettime(h)
Day end time(dayend) = Y=currentyear M=currentmonth D=currentday+1 resettime(h)

Block start time(blockstart) = Y M D h
Block end time(blockend) = Y M D h

if blockstart >= daystart (for all attributes) OR blockend > daystart(for all attributes)
    if blockstart >= daystart (for all attributes) 
        //time is valid. keep it!
        // add to dynamic hoursmissedtotal variable 
    else 
        //set to daystart
       //add to hoursmissedtotal variable
else
    //remove time

**Comment by parkerokonek** [comment]
Making some changes to how files are written to be more in line with how they are stored in memory. I won't be requiring all 24 time blocks to exist in the file as we can infer they haven't been written yet.

Patient Files are structured as follows: (in README)

```
Patient ID:
Feeding Type:
Total Daily Volume:
Max Feeding Rate:
Time & Date of Feeding Day:
timeblock 0
timeblock 1
...
timeblock 23

New data type
timeblock:
missed
rate
```
